builtin_groups:
  name: 内建分组
  description: 包含所有脚本初始分组配置
  groups:
    - default
    - read_later
    - search_default
    - search_group_web
    - search_group_ai
    - community_group
    - site-github.com-repo
    - site-v2ex.com
    - site-linux.do
    - site-2libra.com-invite
    - site-2libra.com
    - site-2libra.com-post
    - other

all_search_groups:
  name: 所有搜索分组
  description: 包含所有搜索引擎相关的分组
  groups:
    - search_group_web
    - search_group_ai
    - search_group_image
    - search_group_translate
    - search_group_sociality
    - search_group_knowledge
    - search_group_video
    - search_group_shopping
    - search_group_scholar
    - search_group_userscript
    - search_group_extension

plugin_groups:
  name: 插件分组
  description: 包含用户脚本和浏览器扩展的分组
  groups:
    - search_group_userscript
    - search_group_extension

github_groups:
  name: GitHub 分组
  description: GitHub 站点相关分组
  groups:
    - site-github.com-repo
    - site-github.com-utils

2libra_groups:
  name: 2libra 分组
  description: 2libra 站点相关分组
  groups:
    - site-2libra.com
    - site-2libra.com-post
    - site-2libra.com-invite

all_groups:
  name: 所有分组
  description: 包含所有已知的分组配置
  groups:
    - default
    - read_later
    - search_default
    - search_group_web
    - search_group_ai
    - search_group_image
    - search_group_translate
    - search_group_sociality
    - search_group_knowledge
    - search_group_video
    - search_group_shopping
    - search_group_scholar
    - search_group_userscript
    - search_group_extension
    - site-github.com-repo
    - site-github.com-utils
    - site-v2ex.com
    - site-linux.do
    - site-2libra.com
    - site-2libra.com-post
    - site-2libra.com-invite
    - community_group
    - other
