all_search_groups:
  name: 所有搜索分组
  description: 包含所有搜索引擎相关的分组
  groups:
    - search_group_web
    - search_group_ai
    - search_group_image
    - search_group_translate
    - search_group_sociality
    - search_group_knowledge
    - search_group_video
    - search_group_shopping
    - search_group_scholar
    - search_group_userscript
    - search_group_extension

plugin_groups:
  name: 插件分组
  description: 包含用户脚本和浏览器扩展的分组
  groups:
    - search_group_userscript
    - search_group_extension

2libra_groups:
  name: 2libra 分组
  description: 2libra 站点相关分组
  groups:
    - site-2libra.com
    - site-2libra.com-post

all_groups:
  name: 所有分组
  description: 包含所有已知的分组配置
  groups:
    - search_group_web
    - search_group_ai
    - search_group_image
    - search_group_translate
    - search_group_sociality
    - search_group_knowledge
    - search_group_video
    - search_group_shopping
    - search_group_scholar
    - search_group_userscript
    - search_group_extension
    - site-github.com-repo
    - site-v2ex.com
    - site-linux.do
    - site-2libra.com
    - site-2libra.com-post
